CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_type VARCHAR(20) NOT NULL,
    document_number VARCHAR(30) NOT NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(254),
    phone VARCHAR(30),
    address VARCHAR(250),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_customers_document_type
        CHECK (document_type IN ('DNI', 'RUC', 'CE', 'PASSPORT', 'OTHER')),
    CONSTRAINT uk_customers_document
        UNIQUE (document_type, document_number)
);

CREATE INDEX ix_customers_active ON customers (active);
