CREATE TABLE suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ruc VARCHAR(11) NOT NULL,
    business_name VARCHAR(150) NOT NULL,
    trade_name VARCHAR(150),
    email VARCHAR(254),
    phone VARCHAR(30),
    address VARCHAR(250),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_suppliers_ruc UNIQUE (ruc),
    CONSTRAINT ck_suppliers_ruc_format CHECK (ruc ~ '^[0-9]{11}$')
);

CREATE INDEX ix_suppliers_active ON suppliers (active);

CREATE TABLE supplier_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id BIGINT NOT NULL,
    product_id BIGINT NOT NULL,
    supplier_product_code VARCHAR(80),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_supplier_products_supplier_product UNIQUE (supplier_id, product_id),
    CONSTRAINT fk_supplier_products_supplier
        FOREIGN KEY (supplier_id) REFERENCES suppliers (id) ON DELETE RESTRICT,
    CONSTRAINT fk_supplier_products_product
        FOREIGN KEY (product_id) REFERENCES products (id) ON DELETE RESTRICT
);

CREATE INDEX ix_supplier_products_supplier_active ON supplier_products (supplier_id, active);
CREATE INDEX ix_supplier_products_product_active ON supplier_products (product_id, active);
