spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/gestion_comercial}
    username: ${DB_USERNAME:gestion_comercial}
    password: ${DB_PASSWORD}
logging:
  level:
    com.gestioncomercial.api: DEBUG

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
